### ISSUE TITLE
Getting chat out of beta: to-do list

### ISSUE THREAD

**Issue by ConnorAhern** [Prodigy-Chat/server#1]
# To-Do list for getting chat out of beta
Sorted from most to least important
- [ ] Make the chat mobile-friendly **(being worked on)**
- [ ] Add a PM/GC system
- [ ] Add an online/offline system (quite easy, plan in comments below) **(being worked on)**
- [ ] Recreate scripts like Away, ChatHacks, Pings, etc.
- [ ] Switch hosting providers or find something to do about the hits limit (i.e. switching to WebSockets)
- [ ] Fix the design glitches, re-add features that got removed when chat had to be reverted a few days back **(being worked on)**
- [ ] Add one-time payment that allows the user to browse ad-free/use custom emojis & a custom profile picture **(being worked on)**
- [ ] Add a Special:Chat page w/ an iframe to the PMGW (idea below in comments)
- [ ] Remove index.php from URLs; stop `/chat` from redirecting to 403 forbidden; delete old folders; remove the useless ar.likesyou.org domain and put it on another host; etc.

**Comment by NameIsA** [comment]
some ideas
![Screenshot_73](https://user-images.githubusercontent.com/61570792/104260875-270d8a80-5439-11eb-8d2d-9a81c2c32764.png)

**Comment by NameIsA** [comment]
dead because fandom hates people expanding their wiki if they dont profit from it

**Comment by ConnorAhern** [comment]
ok now this is no longer fandom so woo

**Comment by afkvido** [comment]
question: how do i add this to my prodigy?

**Comment by ConnorAhern** [comment]
https://chrome.google.com/webstore/detail/prodigy-chat/nlfpeojcafkcoekoeinbhnahfffkgcgc

but its kinda broken rn
